
title: Documentation
description: >- # this means to ignore newlines until "baseurl:"
  When reviewing a PR for this repo, you can see what the documentation,
  e.g. the storybook, will look like when published for the branches
  named above.
baseurl: "" # the subpath of your site, e.g. /blog
url: "" # the base hostname & protocol for your site, e.g. http://example.com

# Build settings
theme: minima
plugins:
  - jekyll-feed

collections:
  branches:
    output: true
    permalink: /branches/:path/

repo_name: "TBD"


repo: ucsb-cs156-f24/team01-f24-12
owner: ucsb-cs156-f24
repo_name: team01-f24-12
pull_requests: [{"author":{"id":"MDQ6VXNlcjMwOTE2MDI3","is_bot":false,"login":"jzipkin1812","name":"Javin Zipkin"},"headRefName":"jz-Recommend-Get","number":60,"title":"Fixed mutation coverage","url":"https://github.com/ucsb-cs156-f24/team01-f24-12/pull/60"},{"author":{"id":"MDQ6VXNlcjMwNjMzMDE5","is_bot":false,"login":"mayarosenbaum","name":""},"headRefName":"Maya-HelpRequest","number":59,"title":"Maya help request","url":"https://github.com/ucsb-cs156-f24/team01-f24-12/pull/59"}]
