
title: Documentation
description: >- # this means to ignore newlines until "baseurl:"
  When reviewing a PR for this repo, you can see what the documentation,
  e.g. the storybook, will look like when published for the branches
  named above.
baseurl: "" # the subpath of your site, e.g. /blog
url: "" # the base hostname & protocol for your site, e.g. http://example.com

# Build settings
theme: minima
plugins:
  - jekyll-feed

collections:
  branches:
    output: true
    permalink: /branches/:path/

repo_name: "TBD"


repo: ucsb-cs156-f24/team01-f24-12
owner: ucsb-cs156-f24
repo_name: team01-f24-12
pull_requests: [{"author":{"id":"U_kgDOCEgVBw","is_bot":false,"login":"yungongWang","name":""},"headRefName":"yungong_3","number":53,"title":"finished creating ArticlesController with GET(all) and POST","url":"https://github.com/ucsb-cs156-f24/team01-f24-12/pull/53"},{"author":{"id":"U_kgDOB8qFSg","is_bot":false,"login":"yixuan-wong","name":""},"headRefName":"yx-UCSBDiningCommonsMenuItem-create-delete","number":51,"title":"yx - ucsb dining commons menu item create delete","url":"https://github.com/ucsb-cs156-f24/team01-f24-12/pull/51"}]
